openapi: 3.0.3
info:
  title: search businesses API
  description: API for search businesses application
  termsOfService: http://swagger.io/terms/
  contact:
    email: splotnikov@gmail.com
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  version: 1.0.0
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
  - url: /api/v1
  - url: http://localhost:3010/api/v1
    description: local
tags:
  - name: greeting
    description: Greeting APIs

paths:
  /hello:
    get:
      description: Returns 'Hello <name>/stranger!!!' to the caller
      tags:
        - greeting
      operationId: hello
      parameters:
        - name: name
          required: false
          in: query
          description: The name of a caller
          schema:
            type: string
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HelloResponse'
  /goodbye:
    get:
      description: Returns 'Goodbye \<name\>!!!' to the authenticated caller
      tags:
        - greeting
      operationId: goodbye
      security:
        - apiKey: []
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HelloResponse'

components:
  securitySchemes:
    apiKey:
      type: http
      scheme: bearer
  schemas:
    HelloResponse:
      type: object
      additionalProperties: false
      required:
        - message
      properties:
        message:
          type: string
