// Location reducer types
export const DETECTING_LOCATION = 'DETECTING_LOCATION'
export const SET_LOCATION = 'SET_LOCATION'
export const SET_LOCATION_UNKNOWN = 'SET_LOCATION_UNKNOWN'
export const SET_LOCATION_ERROR = 'SET_LOCATION_ERROR'
export const CLEAR_LOCATION_ERROR = 'CLEAR_LOCATION_ERROR'

// Data reducer types
export const LOADING_DATA = 'LOADING_DATA'
export const PERFORMING_SEARCH = 'PERFORMING_SEARCH'
export const SET_SEARCH_RESULTS = 'SET_SEARCH_RESULTS'
export const LOADING_DETAIL = 'LOADING_DETAIL'
export const SET_DETAIL = 'SET_DETAIL'
export const SET_DATA_ERRORS = 'SET_DATA_ERRORS'
export const CLEAR_DATA_ERRORS = 'CLEAR_DATA_ERRORS'

// Auth reducer types
export const SET_AUTHENTICATED = 'SET_AUTHENTICATED'
export const CLEAR_AUTH_ERROR = 'CLEAR_AUTH_ERROR'
export const SIGN_OUT = 'SIGN_OUT'
export const ADD_AUTH_ERROR = 'ADD_AUTH_ERROR'

// CDP reducer types
export const SET_OFFERS = 'SET_OFFERS'
export const SET_BROWSER_ID = 'SET_BROWSER_ID'
