name: API Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./businesses-api
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image for API
      run: docker build . --file Dockerfile --tag businesses-api:$(date +%s)
